CREATE TABLE IF NOT EXISTS roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert Roles
INSERT INTO roles (name) VALUES
  ('USER'),
  ('ADMIN');
  ON CONFLICT (name) DO NOTHING;

