CREATE TABLE IF NOT EXISTS roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert Roles
INSERT INTO roles (name, created_at) VALUES
  ('USER', NOW()),
  ('ADMIN', NOW());
  ON CONFLICT (name) DO NOTHING;

